server:
  port: 7002

eureka:
  instance:
    #若在一台电脑上面进行运行，那么需要在C:\windows\System32\driver\host(windos);\etc\host(Linux)中添加修改127.0.0.1   eureka7002.com
    hostname: eureka7002.com #eureka服务端的实列名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实列，并不需要去检测服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      server:
        #关闭自我保护机制，保证不可用服务被及时删除
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 2000